# Generated by Django 3.2.4 on 2025-09-06 15:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0024_alter_ordermodel_paid_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'ordering': ['-created_at'], 'verbose_name': 'Billing Address', 'verbose_name_plural': 'Billing Addresses'},
        ),
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='stripemodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stripe Payment Card', 'verbose_name_plural': 'Stripe Payment Cards'},
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the order', max_length=20),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stripemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(help_text='City name', max_length=120),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='house_no',
            field=models.CharField(help_text='House/building number and street address', max_length=300),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='landmark',
            field=models.CharField(help_text='Nearby landmark for easy identification', max_length=120),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='name',
            field=models.CharField(help_text='Full name for delivery', max_length=200),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='phone_number',
            field=models.CharField(help_text='Contact phone number', max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number')]),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='pin_code',
            field=models.CharField(help_text='PIN/postal code', max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'PIN code must be 6 digits')]),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(help_text='State or province', max_length=120),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='user',
            field=models.ForeignKey(default=1, help_text='User who owns this billing address', on_delete=django.db.models.deletion.CASCADE, related_name='billing_addresses', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.CharField(default='delhi', help_text='Delivery address for this order', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='card_number',
            field=models.CharField(blank=True, default='0000000000000000', help_text='Last 4 digits of payment card', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when order was delivered', null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='is_delivered',
            field=models.BooleanField(default=False, help_text='Whether the order has been delivered'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='name',
            field=models.CharField(help_text='Customer name for this order', max_length=120),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='ordered_item',
            field=models.CharField(default='Not Set', help_text='Description of ordered items', max_length=200),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when payment was completed', null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='paid_status',
            field=models.BooleanField(default=False, help_text='Whether the order has been paid'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total order amount', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(default=1, help_text='User who placed this order', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripemodel',
            name='address_city',
            field=models.CharField(default='Delhi', help_text='City for billing address', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripemodel',
            name='address_country',
            field=models.CharField(default='India', help_text='Country for billing address', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripemodel',
            name='address_state',
            field=models.CharField(default='Delhi', help_text='State for billing address', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripemodel',
            name='address_zip',
            field=models.CharField(default=110051, help_text='ZIP/postal code for billing address', max_length=6, validators=[django.core.validators.RegexValidator('^\\d{5,6}$', 'ZIP code must be 5-6 digits')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripemodel',
            name='card_id',
            field=models.CharField(default='pm_card_visa', help_text='Stripe card ID', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripemodel',
            name='card_number',
            field=models.CharField(default='0000000000000000', help_text='Last 4 digits of card number (for display purposes)', max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'Card number must be 16 digits')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripemodel',
            name='customer_id',
            field=models.CharField(default='0000-0000-0000-0000', help_text='Stripe customer ID', max_length=200),
        ),
        migrations.AlterField(
            model_name='stripemodel',
            name='email',
            field=models.EmailField(default='example@gmail.com', help_text='Email associated with the Stripe customer', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripemodel',
            name='exp_month',
            field=models.CharField(default=3, help_text='Card expiration month (MM format)', max_length=2, validators=[django.core.validators.RegexValidator('^(0[1-9]|1[0-2])$', 'Month must be 01-12')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripemodel',
            name='exp_year',
            field=models.CharField(default=2026, help_text='Card expiration year (YYYY format)', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Year must be 4 digits')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripemodel',
            name='name_on_card',
            field=models.CharField(default='dummy', help_text='Name as it appears on the card', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripemodel',
            name='user',
            field=models.ForeignKey(default=1, help_text='User who owns this payment card', on_delete=django.db.models.deletion.CASCADE, related_name='stripe_cards', to='auth.user'),
            preserve_default=False,
        ),
    ]
